### ISSUE TITLE
Differentiable Data Augmentation.

### ISSUE THREAD

**Issue by MaFuyan** [facebookresearch/radioactive_data#1]
Hi, buddy. I really appreciate it that you make your brilliant work open-sourced.

After diving into your paper, I thought the **Differentiable Data Augmentation** module was pretty interesting. However, I found it was not implemented in src/data_augmentations/__init__.py. Would you mind sharing how you implement that part?

Thanks in advance.

**Comment by alexandresablayrolles** [comment]
All the code should be in src/data_augmentations/__init__.py, with the class DifferentiableDataAugmentation and its children CenterCrop and RandomResizedCropFlip.
