### ISSUE TITLE
Unknown/missing config file

### ISSUE THREAD

**Issue by zzzucf** [facebookresearch/radioactive_data#7]
When to generate the radioactive data, the below line in ~/src/datasets.py line 48 throw an error.

SUBCLASSES = {
    "imagenet": {
        n_cl: list(np.load("/private/home/asablayrolles/data/radioactive/imagenet_classes/%d.npy" % n_cl)) for n_cl in [10, 20, 50, 100, 200, 500]
    }
}

Can you explain what does this file do? what is 10.npy? and how to fix that? Best regards.

**Comment by alexandresablayrolles** [comment]
You can comment out this line, it's in the case where you want to use imagenet with a lower number of classes (in which case each file has a list of the classes that you use).
